name: inferelator
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.2
  - intel-openmp=2020.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - mkl=2020.1
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.1.1
  - python=3.8.3
  - readline=8.0
  - setuptools=47.3.0
  - sqlite=3.32.2
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - anndata==0.7.3
    - bio-test-artifacts==0.1.0
    - bokeh==2.1.0
    - click==7.1.2
    - cloudpickle==1.4.1
    - coverage==5.1
    - cycler==0.10.0
    - dask==2.19.0
    - dask-jobqueue==0.7.1
    - dill==0.3.2
    - distributed==2.19.0
    - fsspec==0.7.4
    - h5py==2.10.0
    - heapdict==1.0.1
    - inferelator==0.4.0
    - jinja2==2.11.2
    - joblib==0.15.1
    - kiwisolver==1.2.0
    - locket==0.2.0
    - markupsafe==1.1.1
    - matplotlib==3.2.2
    - msgpack==1.0.0
    - multiprocess==0.70.10
    - natsort==7.0.1
    - nose==1.3.7
    - numexpr==2.7.1
    - numpy==1.19.0
    - packaging==20.4
    - pandas==1.0.5
    - partd==1.1.0
    - pathos==0.2.6
    - pillow==7.1.2
    - pox==0.2.8
    - ppft==1.6.6.2
    - psutil==5.7.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - six==1.15.0
    - sortedcontainers==2.2.2
    - sparse-dot-mkl==0.5.1
    - tables==3.6.1
    - tblib==1.6.0
    - threadpoolctl==2.1.0
    - toolz==0.10.0
    - tornado==6.0.4
    - typing-extensions==3.7.4.2
    - zict==2.0.0

