name: CellProphet
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - r
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - ca-certificates
  - libgcc-ng
  - libstdcxx-ng
  - libzlib
  - openssl
  - python=3.10.13
  - pip=24.0
  - setuptools=69.1.1
  - wheel=0.42.0
  - blas
  - pybedtools
